name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello"
      - name: print by
        run: echo "bye"
      - name: multiple runs
        run: |
          echo "First output"
          echo "Second output"
  
