name: Share data between jobs

on: push

jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - name: Enable runner debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      - name: Enable step debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Create file
        run: echo "Hello World" > file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Enable runner debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      - name: Enable step debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: file
      - name: Display file contents
        run: cat file.txt

  download_logs:
    name: Get Workflow Run Logs
    runs-on: ubuntu-latest
    needs: [job_1, job_2]
    steps:
      - name: Install unzip
        run: sudo apt-get install -y unzip
      - name: Get Workflow Logs
        run: |
          curl -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -L "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs" \
               --output workflow_logs.zip
      - name: Check if log file exists
        run: |
          if [ ! -f workflow_logs.zip ]; then
            echo "Log file not found!";
            exit 1;
          fi
          echo "Log file downloaded successfully."
      - name: Extract Logs
        run: |
          echo "Attempting to unzip workflow_logs.zip"
          unzip -v workflow_logs.zip
      - name: Display Log Files
        run: ls -R logs
