name: Share data between jobs

on: push

jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - name: Enable runner debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      - name: Enable step debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Create file
        run: echo "Hello World" > file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Enable runner debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      - name: Enable step debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: file
      - name: Display file contents
        run: cat file.txt
