name: Job Approval Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building the project..."

  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Await manual approval
        uses: actions/pause-for-approval@v1
        with:
          approval_message: "Please approve to proceed to deployment."

  deploy:
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Deploy step
        run: echo "Deployment started after approval."
